services:
  wireguard:
    container_name: wireguard
    build:
      context: ./docker
      dockerfile: Dockerfile
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - type: bind
        source: ./config/wg0.conf
        target: /etc/wireguard/wg0.conf
    ports:
      - name: wireguard
        published: 51820
        target: 51820
        protocol: udp