services:
  wireguard:
    image: wireguard:latest
    pull_policy: build
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: wireguard
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      net.ipv4.ip_forward: 1
      net.ipv4.conf.all.src_valid_mark: 1
    volumes:
      - type: bind
        source: ./config/wg0.conf
        target: /etc/wireguard/wg0.conf
    networks:
      - wireguard-net
    ports:
      - published: 51820
        target: 51820
        protocol: udp

networks:
  wireguard-net:
    name: wireguard
